# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('keyman', models.CharField(blank=True, max_length=20)),
                ('contact_information', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('spec', models.CharField(blank=True, max_length=100)),
                ('comment', models.CharField(blank=True, max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csorder.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20)),
                ('customer_orderno', models.CharField(blank=True, max_length=20)),
                ('order_date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csorder.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_qty', models.DecimalField(decimal_places=0, max_digits=6)),
                ('ship_total_qty', models.DecimalField(decimal_places=0, max_digits=6)),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('customer_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csorder.Customer_Product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csorder.Order')),
            ],
            options={
                'ordering': ['customer_product', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Ship_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_date', models.DateField()),
                ('ship_qty', models.DecimalField(decimal_places=0, max_digits=6)),
                ('blno', models.CharField(blank=True, max_length=20)),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csorder.Order_Detail')),
            ],
            options={
                'ordering': ['order_detail'],
            },
        ),
        migrations.CreateModel(
            name='TempView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('customer_orderno', models.CharField(blank=True, max_length=20)),
                ('order_date', models.DateField()),
                ('order_qty', models.DecimalField(decimal_places=0, max_digits=6)),
                ('ship_date', models.DateField()),
                ('ship_qty', models.DecimalField(decimal_places=0, max_digits=6)),
                ('ship_total_qty', models.DecimalField(decimal_places=0, max_digits=6)),
                ('remained_qty', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
    ]
